import { ButtonStyle } from "./types";

export const getCodeTextTs = (buttonProps: ButtonStyle): string => {
  return `import { Button, SxProps, Theme } from "@mui/material";
import React from "react";

const style: SxProps<Theme> = {
  textTransform: "none",
  borderRadius: 2,
  color: "${buttonProps.color}",
  backgroundColor: "${buttonProps.bgColor}",
  border: "1px solid ${buttonProps.borderColor}",
  "&:hover": {
    backgroundColor: "${buttonProps.hoverColor}",
  },
  "&:active": {
    backgroundColor: "${buttonProps.activeColor}",
  },
};

const CustomButton: React.FC = () => {
  return <Button sx={style}>${buttonProps.text}</Button>;
};

export default CustomButton;`;
};

export const getCodeTextJs = (buttonProps: ButtonStyle): string => {
  return `import { Button } from "@mui/material";
import React from "react";

const style = {
  textTransform: "none",
  borderRadius: 2,
  color: "${buttonProps.color}",
  backgroundColor: "${buttonProps.bgColor}",
  border: "1px solid ${buttonProps.borderColor}",
  "&:hover": {
    backgroundColor: "${buttonProps.hoverColor}",
  },
  "&:active": {
    backgroundColor: "${buttonProps.activeColor}",
  },
};

const CustomButton = () => {
  return <Button sx={style}>${buttonProps.text}</Button>;
};

export default CustomButton;`;
};

export const getButtonColor = (buttonProps: ButtonStyle): string => {
  return `  {
    text: "ボタン",
    color: "${buttonProps.color}",
    bgColor: "${buttonProps.bgColor}",
    hoverColor: "${buttonProps.hoverColor}",
    activeColor: "${buttonProps.activeColor}",
    borderColor: "${buttonProps.borderColor}",
  },`;
};

export const getRandomButton = (): ButtonStyle => {
  let text = "ボタン";
  if (0.3 < Math.random()) {
    text = randomTextJp[Math.floor(Math.random() * randomTextJp.length)];
  } else {
    text = randomTextEn[Math.floor(Math.random() * randomTextEn.length)];
  }
  return {
    ...randomButtonColors[
      Math.floor(Math.random() * randomButtonColors.length)
    ],
    text: text,
  };
};

export const randomTextJp: string[] = [
  "開始",
  "終了",
  "受け取り",
  "登録",
  "編集",
  "閉じる",
  "開く",
  "検索",
  "作成",
  "印刷",
  "前へ",
  "次へ",
  "戻る",
  "進む",
  "受信",
  "有効",
  "無効",
  "書込み",
  "複製",
  "貼り付け",
  "切り取り",
  "クリア",
  "はい",
  "いいえ",
  "完了",
  "中止",
  "確認",
  "修正",
  "続行",
  "参照",
  "リロード",
  "リフレッシュ",
  "リセット",
  "ロック",
  "アンロック",
  "拡大",
  "縮小",
  "詳細",
  "キャンセル",
  "リトライ",
  "保存",
  "メニュー",
  "オプション",
  "スタート",
  "フィニッシュ",
  "送信",
  "更新",
  "適用",
  "復元",
  "中断",
  "見る",
  "閲覧",
  "読取り",
  "読み取る",
  "エクスポート",
  "インポート",
  "ソート",
  "フィルタ",
  "スクロール",
  "取消",
  "取り消す",
  "やり直す",
  "分割",
  "結合",
  "挿入",
  "設定",
  "コネクト",
  "接続",
  "切断",
  "インストール",
  "一時停止",
  "停止",
  "ストップ",
  "再開",
  "交換",
  "リンク",
  "解除",
  "一括削除",
  "削除",
  "デリート",
  "実行",
  "共有",
  "シェア",
  "選択解除",
  "複数選択",
  "選択",
  "セレクト",
  "ログイン",
  "ログアウト",
  "サインイン",
  "サインアップ",
];

const randomTextEn: string[] = [
  "Start",
  "Finish",
  "End",
  "Register",
  "Edit",
  "Close",
  "Open",
  "Print",
  "Search",
  "Return",
  "Enable",
  "Disable",
  "Write",
  "Read",
  "Clear",
  "Paste",
  "Reload",
  "Confirm",
  "Modify",
  "Stop",
  "Refresh",
  "Reset",
  "Lock",
  "Unlock",
  "Retry",
  "Save",
  "Menu",
  "Option",
  "Settings",
  "Update",
  "Upload",
  "Download",
  "Export",
  "Import",
  "Sort",
  "Filter",
  "Scroll",
  "Insert",
  "Install",
  "Connect",
  "Disconnect",
  "Restart",
  "Share",
  "Good",
  "Favorite",
  "Login",
  "Logout",
  "Sign in",
  "Sign out",
  "Sing up",
  "Apply",
  "Cancel",
  "Detail",
  "Shrink",
  "End",
  "Yes",
  "No",
  "YES",
  "NO",
  "Next",
  "On",
  "Off",
  "ON",
  "OFF",
];

export const randomButtonColors: ButtonStyle[] = [
  {
    text: "ボタン",
    color: "#f9f9fbff",
    bgColor: "#446de3",
    hoverColor: "#4484e4",
    activeColor: "#377ce4",
    borderColor: "#377ce4",
  },
  {
    text: "ボタン",
    color: "#a8f7d2ff",
    bgColor: "#465644ff",
    hoverColor: "#408639ff",
    activeColor: "#4a6e37ff",
    borderColor: "#9ecd99ff",
  },
  {
    text: "ボタン",
    color: "#107e4bff",
    bgColor: "#49ef2bff",
    hoverColor: "#3be339ff",
    activeColor: "#4ede79ff",
    borderColor: "#2fc251ff",
  },
  {
    text: "ボタン",
    color: "#ffffffff",
    bgColor: "#35c11dff",
    hoverColor: "#3be339ff",
    activeColor: "#4ede79ff",
    borderColor: "#ddf2e3ff",
  },
  {
    text: "ボタン",
    color: "#ffffffff",
    bgColor: "#3a8f2dff",
    hoverColor: "#3be339ff",
    activeColor: "#4ede79ff",
    borderColor: "#ddf2e3ff",
  },
  {
    text: "ボタン",
    color: "#ffffffff",
    bgColor: "#3f85b0ff",
    hoverColor: "#4b79b3ff",
    activeColor: "#36618fff",
    borderColor: "#ddf2e3ff",
  },
  {
    text: "ボタン",
    color: "#d26bdfff",
    bgColor: "#e8d5e8ff",
    hoverColor: "#ebceebff",
    activeColor: "#dfc7e1ff",
    borderColor: "#e8b6e8ff",
  },
  {
    text: "ボタン",
    color: "#6b1876ff",
    bgColor: "#ebb3ebff",
    hoverColor: "#ebceebff",
    activeColor: "#dfc7e1ff",
    borderColor: "#9d799dff",
  },
  {
    text: "ボタン",
    color: "#fce6ffff",
    bgColor: "#b53cb5ff",
    hoverColor: "#ae74aeff",
    activeColor: "#a851b0ff",
    borderColor: "#d9c5d9ff",
  },
  {
    text: "ボタン",
    color: "#ebd8ebff",
    bgColor: "#804a80ff",
    hoverColor: "#712171ff",
    activeColor: "#a851b0ff",
    borderColor: "#370d37ff",
  },
  {
    text: "ボタン",
    color: "#000000ff",
    bgColor: "#e6ccd0ff",
    hoverColor: "#e6abadff",
    activeColor: "#f0e0e1ff",
    borderColor: "#dfafb7ff",
  },
  {
    text: "ボタン",
    color: "#000000ff",
    bgColor: "#f9323cff",
    hoverColor: "#e35d67ff",
    activeColor: "#ed5562ff",
    borderColor: "#d5a3abff",
  },
  {
    text: "ボタン",
    color: "#2a1414ff",
    bgColor: "#fb2929ff",
    hoverColor: "#fb0000ff",
    activeColor: "#fa0b0bff",
    borderColor: "#f1d0d0ff",
  },
  {
    text: "ボタン",
    color: "#ffeaeaff",
    bgColor: "#945050ff",
    hoverColor: "#975c5cff",
    activeColor: "#925250ff",
    borderColor: "#f1d0d0ff",
  },
  {
    text: "ボタン",
    color: "#fff6f6ff",
    bgColor: "#8d0b0bff",
    hoverColor: "#8b2121ff",
    activeColor: "#8b1c18ff",
    borderColor: "#f1d0d0ff",
  },
  {
    text: "ボタン",
    color: "#fbf9f9ff",
    bgColor: "#e34444ff",
    hoverColor: "#e44444ff",
    activeColor: "#e43d37ff",
    borderColor: "#e43737ff",
  },
  {
    text: "ボタン",
    color: "#4a0b11ff",
    bgColor: "#f10e1dff",
    hoverColor: "#cd8287ff",
    activeColor: "#ed5562ff",
    borderColor: "#d5a3abff",
  },
  {
    text: "ボタン",
    color: "#fcf6f7ff",
    bgColor: "#fe1236ff",
    hoverColor: "#f04349ff",
    activeColor: "#e4515aff",
    borderColor: "#dfafb7ff",
  },
  {
    text: "ボタン",
    color: "#c85367ff",
    bgColor: "#f9d1d6ff",
    hoverColor: "#f0d3d4ff",
    activeColor: "#f4e5e6ff",
    borderColor: "#f0c7ceff",
  },
  {
    text: "ボタン",
    color: "#e3369bff",
    bgColor: "#f0bbddff",
    hoverColor: "#eba6cfff",
    activeColor: "#e399d4ff",
    borderColor: "#c89bb4ff",
  },
  {
    text: "ボタン",
    color: "#fdfcffff",
    bgColor: "#662bc2ff",
    hoverColor: "#5840c8ff",
    activeColor: "#504caeff",
    borderColor: "#d6d5f0ff",
  },
  {
    text: "ボタン",
    color: "#493584ff",
    bgColor: "#c6b3e3ff",
    hoverColor: "#c0badcff",
    activeColor: "#a8a6daff",
    borderColor: "#8482dcff",
  },
  {
    text: "ボタン",
    color: "#f2f0f7ff",
    bgColor: "#8850deff",
    hoverColor: "#6b55d7ff",
    activeColor: "#3a34c9ff",
    borderColor: "#6c68baff",
  },
  {
    text: "ボタン",
    color: "#f7feffb3",
    bgColor: "#9d73dfff",
    hoverColor: "#5744b5ff",
    activeColor: "#3b35b8ff",
    borderColor: "#cccaebff",
  },
  {
    text: "ボタン",
    color: "#0132f9ff",
    bgColor: "#c8d2edff",
    hoverColor: "#9dbff0ff",
    activeColor: "#acc8f2ff",
    borderColor: "#8fb7f2ff",
  },
  {
    text: "ボタン",
    color: "#e5e9fbff",
    bgColor: "#0a48f0ff",
    hoverColor: "#387cdfff",
    activeColor: "#3073d7ff",
    borderColor: "#8fb7f2ff",
  },
  {
    text: "ボタン",
    color: "#bec6edff",
    bgColor: "#0c266aff",
    hoverColor: "#123573ff",
    activeColor: "#13356cff",
    borderColor: "#8fb7f2ff",
  },
  {
    text: "ボタン",
    color: "#ffffffff",
    bgColor: "#91a3d5ff",
    hoverColor: "#5b82c6ff",
    activeColor: "#4777c4ff",
    borderColor: "#7094d0ff",
  },
  {
    text: "ボタン",
    color: "#eaeafeff",
    bgColor: "#06319fff",
    hoverColor: "#2d6bceff",
    activeColor: "#4242c8ff",
    borderColor: "#d7e1f0ff",
  },
  {
    text: "ボタン",
    color: "#128989ff",
    bgColor: "#1df1f1ff",
    hoverColor: "#1bcacaff",
    activeColor: "#57acc8ff",
    borderColor: "#8fccf2ff",
  },
  {
    text: "ボタン",
    color: "#d1f4f4ff",
    bgColor: "#17b3b3ff",
    hoverColor: "#388484ff",
    activeColor: "#81d1eaff",
    borderColor: "#5c7586ff",
  },
  {
    text: "ボタン",
    color: "#156c6cff",
    bgColor: "#c1ededff",
    hoverColor: "#82cdcdff",
    activeColor: "#81d1eaff",
    borderColor: "#7094abff",
  },
  {
    text: "ボタン",
    color: "#1c57dbff",
    bgColor: "#32b4f9ff",
    hoverColor: "#74a8f4ff",
    activeColor: "#4d8af1ff",
    borderColor: "#83c4d5ff",
  },
  {
    text: "ボタン",
    color: "#e3e3d7ff",
    bgColor: "#aab934ff",
    hoverColor: "#a4a622ff",
    activeColor: "#b4b52dff",
    borderColor: "#dddfafff",
  },
  {
    text: "ボタン",
    color: "#5e5e39ff",
    bgColor: "#ced978ff",
    hoverColor: "#d3d526ff",
    activeColor: "#eced2dff",
    borderColor: "#b4b763ff",
  },
  {
    text: "ボタン",
    color: "#8e8e39ff",
    bgColor: "#dffd04ff",
    hoverColor: "#d3d526ff",
    activeColor: "#efef1dff",
    borderColor: "#dcdea0ff",
  },
  {
    text: "ボタン",
    color: "#eaea77ff",
    bgColor: "#5f6c02ff",
    hoverColor: "#75760bff",
    activeColor: "#6c6c04ff",
    borderColor: "#ecf166ff",
  },
  {
    text: "ボタン",
    color: "#fbfbf2ff",
    bgColor: "#8e9c2cff",
    hoverColor: "#a8a948ff",
    activeColor: "#6c6c04ff",
    borderColor: "#ecf166ff",
  },
  {
    text: "ボタン",
    color: "#7f5708ff",
    bgColor: "#deb668ff",
    hoverColor: "#e0bb8eff",
    activeColor: "#d5bf62ff",
    borderColor: "#c4ae7cff",
  },
  {
    text: "ボタン",
    color: "#f7eedaff",
    bgColor: "#ffa800ff",
    hoverColor: "#ff9d22ff",
    activeColor: "#fba514ff",
    borderColor: "#c4ae7cff",
  },
  {
    text: "ボタン",
    color: "#957530ff",
    bgColor: "#e5a72aff",
    hoverColor: "#e89227ff",
    activeColor: "#fba514ff",
    borderColor: "#f2e7ceff",
  },
  {
    text: "ボタン",
    color: "#ecddbfff",
    bgColor: "#9f6b02ff",
    hoverColor: "#b06609ff",
    activeColor: "#ba790bff",
    borderColor: "#f2e7ceff",
  },
  {
    text: "ボタン",
    color: "#dec083ff",
    bgColor: "#644301ff",
    hoverColor: "#543001ff",
    activeColor: "#5b3b04ff",
    borderColor: "#f2e7ceff",
  },
  {
    text: "ボタン",
    color: "#3c3424ff",
    bgColor: "#deab46ff",
    hoverColor: "#d5994dff",
    activeColor: "#f19d14ff",
    borderColor: "#f2e7ceff",
  },
  {
    text: "ボタン",
    color: "#0c1b19ff",
    bgColor: "#25f4f4ff",
    hoverColor: "#00e9fbff",
    activeColor: "#0bd9faff",
    borderColor: "#7edae3ff",
  },
  {
    text: "ボタン",
    color: "#0e1b0cff",
    bgColor: "#4bf425ff",
    hoverColor: "#00fb06ff",
    activeColor: "#0bfa2aff",
    borderColor: "#8de37eff",
  },
  {
    text: "ボタン",
    color: "#0c181bff",
    bgColor: "#25edf4ff",
    hoverColor: "#00fbd8ff",
    activeColor: "#0bf2faff",
    borderColor: "#7ed8e3ff",
  },
  {
    text: "ボタン",
    color: "#1a0c1bff",
    bgColor: "#c625f4ff",
    hoverColor: "#fb00f5ff",
    activeColor: "#ef0bfaff",
    borderColor: "#e37ee1ff",
  },
  {
    text: "ボタン",
    color: "#1a1b0cff",
    bgColor: "#dcf425ff",
    hoverColor: "#d5fb00ff",
    activeColor: "#f7fa0bff",
    borderColor: "#d7e37eff",
  },
  {
    text: "ボタン",
    color: "#1b150cff",
    bgColor: "#f49925ff",
    hoverColor: "#fbb800ff",
    activeColor: "#fa900bff",
    borderColor: "#e3b67eff",
  },
  {
    text: "ボタン",
    color: "#f6f4efff",
    bgColor: "#c07617ff",
    hoverColor: "#be8515ff",
    activeColor: "#b77420ff",
    borderColor: "#81705dff",
  },
  {
    text: "ボタン",
    color: "#eff6f5ff",
    bgColor: "#17c0a2ff",
    hoverColor: "#15beb2ff",
    activeColor: "#20b7acff",
    borderColor: "#67978fff",
  },
  {
    text: "ボタン",
    color: "#eff6f2ff",
    bgColor: "#17c050ff",
    hoverColor: "#15be3cff",
    activeColor: "#20b74eff",
    borderColor: "#67976bff",
  },
  {
    text: "ボタン",
    color: "#eff0f6ff",
    bgColor: "#0129d9ff",
    hoverColor: "#1548beff",
    activeColor: "#2048b7ff",
    borderColor: "#677997ff",
  },
  {
    text: "ボタン",
    color: "#f6eff4ff",
    bgColor: "#d901aeff",
    hoverColor: "#be158bff",
    activeColor: "#b72089ff",
    borderColor: "#976788ff",
  },
  {
    text: "ボタン",
    color: "#f4eff6ff",
    bgColor: "#9a01d9ff",
    hoverColor: "#b615beff",
    activeColor: "#9020b7ff",
    borderColor: "#976796ff",
  },
  {
    text: "ボタン",
    color: "#f5f6efff",
    bgColor: "#cfd901ff",
    hoverColor: "#b0be15ff",
    activeColor: "#abb720ff",
    borderColor: "#959767ff",
  },
  {
    text: "ボタン",
    color: "#eff2f6ff",
    bgColor: "#0151d9ff",
    hoverColor: "#1560beff",
    activeColor: "#3579bcff",
    borderColor: "#97b2deff",
  },
  {
    text: "ボタン",
    color: "#ffffffff",
    bgColor: "#6f8bdcff",
    hoverColor: "#669ae6ff",
    activeColor: "#377ce4",
    borderColor: "#377ce4",
  },
  {
    text: "ボタン",
    color: "#ffffffff",
    bgColor: "#6fdcb6ff",
    hoverColor: "#66e6b0ff",
    activeColor: "#37e4baff",
    borderColor: "#37e4a8ff",
  },
  {
    text: "ボタン",
    color: "#ffffffff",
    bgColor: "#8fdc6fff",
    hoverColor: "#82e666ff",
    activeColor: "#63e437ff",
    borderColor: "#7be437ff",
  },
  {
    text: "ボタン",
    color: "#ffffffff",
    bgColor: "#ccdc6fff",
    hoverColor: "#d7e666ff",
    activeColor: "#bee437ff",
    borderColor: "#d0e437ff",
  },
  {
    text: "ボタン",
    color: "#ffffffff",
    bgColor: "#dcca6fff",
    hoverColor: "#e6d666ff",
    activeColor: "#e4c237ff",
    borderColor: "#e4c837ff",
  },
  {
    text: "ボタン",
    color: "#ffffffff",
    bgColor: "#dc6f6fff",
    hoverColor: "#e66666ff",
    activeColor: "#e43737ff",
    borderColor: "#e43737ff",
  },
  {
    text: "ボタン",
    color: "#ffffffff",
    bgColor: "#ff0000ff",
    hoverColor: "#e10303ff",
    activeColor: "#fb0000ff",
    borderColor: "#b30f0fff",
  },
  {
    text: "ボタン",
    color: "#ffffffff",
    bgColor: "#ff00e7ff",
    hoverColor: "#e1039eff",
    activeColor: "#fb00ecff",
    borderColor: "#a60fb3ff",
  },
  {
    text: "ボタン",
    color: "#ffffffff",
    bgColor: "#7f00ffff",
    hoverColor: "#6303e1ff",
    activeColor: "#9800fbff",
    borderColor: "#560fb3ff",
  },
  {
    text: "ボタン",
    color: "#ffffffff",
    bgColor: "#00ff3bff",
    hoverColor: "#03e165ff",
    activeColor: "#00fb55ff",
    borderColor: "#0fb341ff",
  },
  {
    text: "ボタン",
    color: "#373737ff",
    bgColor: "#a9a9a9ff",
    hoverColor: "#989898ff",
    activeColor: "#b5b5b5ff",
    borderColor: "#878787ff",
  },
  {
    text: "ボタン",
    color: "#ebebebff",
    bgColor: "#545454ff",
    hoverColor: "#656565ff",
    activeColor: "#656565ff",
    borderColor: "#878787ff",
  },
  {
    text: "ボタン",
    color: "#ebebebff",
    bgColor: "#010101ff",
    hoverColor: "#656565ff",
    activeColor: "#656565ff",
    borderColor: "#878787ff",
  },
  {
    text: "ボタン",
    color: "#ffffffff",
    bgColor: "#010101ff",
    hoverColor: "#464646ff",
    activeColor: "#323232ff",
    borderColor: "#ffffffff",
  },
  {
    text: "ボタン",
    color: "#343434ff",
    bgColor: "#ebebebff",
    hoverColor: "#cbcbcbff",
    activeColor: "#c4c4c4ff",
    borderColor: "#c9c9c9ff",
  },
  {
    text: "ボタン",
    color: "#131313ff",
    bgColor: "#bfbfbfff",
    hoverColor: "#cbcbcbff",
    activeColor: "#c4c4c4ff",
    borderColor: "#8c8c8cff",
  },
  {
    text: "ボタン",
    color: "#000000ff",
    bgColor: "#ffffffff",
    hoverColor: "#ffffffff",
    activeColor: "#f8f8f8ff",
    borderColor: "#d6d6d6ff",
  },
  {
    text: "ボタン",
    color: "#000000ff",
    bgColor: "#d339ffff",
    hoverColor: "#ff2fecff",
    activeColor: "#f400ffff",
    borderColor: "#c48ec1ff",
  },
  {
    text: "ボタン",
    color: "#000000ff",
    bgColor: "#39f1ffff",
    hoverColor: "#2fc5ffff",
    activeColor: "#00caffff",
    borderColor: "#8eb1c4ff",
  },
  {
    text: "ボタン",
    color: "#000000ff",
    bgColor: "#e1ff39ff",
    hoverColor: "#fffa2fff",
    activeColor: "#e1ff00ff",
    borderColor: "#c4b68eff",
  },
  {
    text: "ボタン",
    color: "#010202ff",
    bgColor: "#39fff8ff",
    hoverColor: "#2ff0ffff",
    activeColor: "#00edffff",
    borderColor: "#8ec2c4ff",
  },
  {
    text: "ボタン",
    color: "#010201ff",
    bgColor: "#39ff90ff",
    hoverColor: "#2fff67ff",
    activeColor: "#00ff32ff",
    borderColor: "#92c48eff",
  },
  {
    text: "ボタン",
    color: "#020201ff",
    bgColor: "#fffa39ff",
    hoverColor: "#e7ff2fff",
    activeColor: "#d8ff00ff",
    borderColor: "#c0c48eff",
  },
  {
    text: "ボタン",
    color: "#FFFFFF",
    bgColor: "#446de3",
    hoverColor: "#4484e4",
    activeColor: "#377ce4",
    borderColor: "#377ce4",
  },
  {
    text: "ボタン",
    color: "#FFFFFF",
    bgColor: "#446de3",
    hoverColor: "#4484e4",
    activeColor: "#377ce4",
    borderColor: "#377ce4",
  },
  {
    text: "ボタン",
    color: "#FFFFFF",
    bgColor: "#446de3",
    hoverColor: "#4484e4",
    activeColor: "#377ce4",
    borderColor: "#377ce4",
  },
  {
    text: "ボタン",
    color: "#FFFFFF",
    bgColor: "#446de3",
    hoverColor: "#4484e4",
    activeColor: "#377ce4",
    borderColor: "#377ce4",
  },
  {
    text: "ボタン",
    color: "#ffffffff",
    bgColor: "#010101ff",
    hoverColor: "#464646ff",
    activeColor: "#323232ff",
    borderColor: "#ffffffff",
  },
  {
    text: "ボタン",
    color: "#ffffffff",
    bgColor: "#010101ff",
    hoverColor: "#464646ff",
    activeColor: "#323232ff",
    borderColor: "#ffffffff",
  },
  {
    text: "ボタン",
    color: "#ffffffff",
    bgColor: "#6fdcb6ff",
    hoverColor: "#66e6b0ff",
    activeColor: "#37e4baff",
    borderColor: "#37e4a8ff",
  },
  {
    text: "ボタン",
    color: "#ffffffff",
    bgColor: "#6fdcb6ff",
    hoverColor: "#66e6b0ff",
    activeColor: "#37e4baff",
    borderColor: "#37e4a8ff",
  },
  {
    text: "ボタン",
    color: "#ffffffff",
    bgColor: "#6fdcb6ff",
    hoverColor: "#66e6b0ff",
    activeColor: "#37e4baff",
    borderColor: "#37e4a8ff",
  },
  {
    text: "ボタン",
    color: "#d26bdfff",
    bgColor: "#e8d5e8ff",
    hoverColor: "#ebceebff",
    activeColor: "#dfc7e1ff",
    borderColor: "#e8b6e8ff",
  },
  {
    text: "ボタン",
    color: "#df6b8bff",
    bgColor: "#e8d5daff",
    hoverColor: "#ebced7ff",
    activeColor: "#e1c7cdff",
    borderColor: "#e8b6bdff",
  },
  {
    text: "ボタン",
    color: "#6b92dfff",
    bgColor: "#d5d5e8ff",
    hoverColor: "#ced4ebff",
    activeColor: "#c7cce1ff",
    borderColor: "#b6c7e8ff",
  },
  {
    text: "ボタン",
    color: "#6b92dfff",
    bgColor: "#d5d5e8ff",
    hoverColor: "#ced4ebff",
    activeColor: "#c7cce1ff",
    borderColor: "#b6c7e8ff",
  },
  {
    text: "ボタン",
    color: "#6bdfa6ff",
    bgColor: "#d5e8dfff",
    hoverColor: "#ceebdfff",
    activeColor: "#c7e1d4ff",
    borderColor: "#b6e8bbff",
  },
  {
    text: "ボタン",
    color: "#6bdfa6ff",
    bgColor: "#d5e8dfff",
    hoverColor: "#ceebdfff",
    activeColor: "#c7e1d4ff",
    borderColor: "#b6e8bbff",
  },
  {
    text: "ボタン",
    color: "#c6d237ff",
    bgColor: "#e6e8d5ff",
    hoverColor: "#eaebceff",
    activeColor: "#e0e1c7ff",
    borderColor: "#dfe8b6ff",
  },
  {
    text: "ボタン",
    color: "#c6d237ff",
    bgColor: "#e6e8d5ff",
    hoverColor: "#eaebceff",
    activeColor: "#e0e1c7ff",
    borderColor: "#dfe8b6ff",
  },
  {
    text: "ボタン",
    color: "#3937d2ff",
    bgColor: "#dbd5e8ff",
    hoverColor: "#d9ceebff",
    activeColor: "#ccc7e1ff",
    borderColor: "#b8b6e8ff",
  },
  {
    text: "ボタン",
    color: "#3937d2ff",
    bgColor: "#dbd5e8ff",
    hoverColor: "#d9ceebff",
    activeColor: "#ccc7e1ff",
    borderColor: "#b8b6e8ff",
  },
  {
    text: "ボタン",
    color: "#d23783ff",
    bgColor: "#e8d5deff",
    hoverColor: "#ebcee0ff",
    activeColor: "#e1c7d2ff",
    borderColor: "#e8b6cdff",
  },
];
